#!/usr/bin/env python3

import argparse

from pareidolia import randomize


parser = argparse.ArgumentParser(description='Create image for pareidolia')
parser.add_argument('--images', '-i', nargs='+', dest='images',
                    help='images to be processed')
parser.add_argument('--number', '-n', dest='number', type=int,
                    help='number of images to be created')

args = parser.parse_args()

randomize(args.images, number=args.number)
